
document.addEventListener('DOMContentLoaded', async () => {
    // Corrected ID to match the template generated by owner2.html
    const mountPoint = document.getElementById('dynamic-pagination');
    
    const getCurrentPart = () => {
        const match = window.location.pathname.match(/-part-(\d+)\.html$/);
        return match ? parseInt(match[1]) : 1;
    };

    const currentPage = getCurrentPart();

    if (mountPoint) {
        const categoryKey = mountPoint.dataset.category;
        
        try {
            const res = await fetch('/data/page-counts.json?cache=' + Date.now());
            if (res.ok) {
                const data = await res.json();
                const totalPages = data[categoryKey] || 1;

                if (totalPages > 1) {
                    renderPagination(mountPoint, currentPage, totalPages);
                }
            }
        } catch (e) {
            console.error("Pagination load failed:", e);
        }
    }

    // Language Link Fix (Keep same part number)
    updateLangBtn(currentPage);
});

function renderPagination(container, current, total) {
    let html = '<div class="pagination-wrapper" style="text-align:center; margin:30px 0;">';
    
    // THE LINE YOU REQUESTED: Showing current page vs total
    html += `<div class="page-info" style="margin-bottom:12px; font-weight:700; color:var(--text-secondary); font-size:1rem;">Page ${current} of ${total}</div>`;
    
    html += '<div class="pagination-buttons" style="display:flex; justify-content:center; gap:8px; flex-wrap:wrap; align-items:center;">';
    
    let path = window.location.pathname;
    let filename = path.split('/').pop();
    let baseUrl = filename.replace(/-part-\d+\.html$/, '').replace(/\.html$/, '');
    
    const getUrl = (p) => p === 1 ? `${baseUrl}.html` : `${baseUrl}-part-${p}.html`;

    // Prev Button
    if (current > 1) {
        html += `<a href="${getUrl(current - 1)}" class="button" style="border:1px solid #ccc; padding:8px 14px; border-radius:6px; text-decoration:none; color:var(--text-primary); background:var(--card-bg); font-weight:600;">&laquo; Prev</a>`;
    }

    // Page Numbers logic (Show 1, current-1, current, current+1, last)
    const show = new Set([1, total, current, current-1, current+1]);
    let prevShown = 0;

    for (let i = 1; i <= total; i++) {
        if (show.has(i)) {
            if (i - prevShown > 1) html += `<span style="padding:8px; color:#aaa;">...</span>`;
            
            if (i === current) {
                html += `<span class="active" style="background:var(--accent-color); color:white; padding:8px 16px; border-radius:6px; font-weight:bold; border:1px solid var(--accent-color);">${i}</span>`;
            } else {
                html += `<a href="${getUrl(i)}" class="button" style="border:1px solid #ccc; padding:8px 14px; border-radius:6px; text-decoration:none; color:var(--text-primary); background:var(--card-bg);">${i}</a>`;
            }
            
            prevShown = i;
        }
    }

    // Next Button
    if (current < total) {
        html += `<a href="${getUrl(current + 1)}" class="button" style="border:1px solid #ccc; padding:8px 14px; border-radius:6px; text-decoration:none; color:var(--text-primary); background:var(--card-bg); font-weight:600;">Next &raquo;</a>`;
    }

    html += '</div></div>';
    container.innerHTML = html;
}

function updateLangBtn(part) {
    const btn = document.querySelector('.link-container .link-button');
    if (!btn) return;
    const href = btn.getAttribute('href');
    if (!href) return;

    let base = href.replace(/-part-\d+\.html$/, '').replace(/\.html$/, '');
    if (part > 1) {
        btn.setAttribute('href', `${base}-part-${part}.html`);
    } else {
        btn.setAttribute('href', `${base}.html`);
    }
}
