title: GK Learn Study
description: "Your one-stop destination for knowledge, tools, and tutorials"
baseurl: "" # agar custom domain hai to yaha blank hi rakho
url: "https://gklearnstudy.in"
theme: minima   # abhi ke liye default theme use karo
