# सभी JS फ़ाइलों के लिए हेडर
[[headers]]
  for = "/*.js"  # केवल JavaScript फाइलों पर लागू
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# सभी अन्य फाइलों के लिए हेडर (HTML, CSS, Images आदि)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
