# सभी JS फ़ाइलों के लिए हेडर
[[headers]]
  for = "/*.js"  # सभी JS फ़ाइलों पर लागू होगा
  [headers.values]
    Cache-Control = "max-age=31536000"  # कैश को अधिकतम समय तक स्टोर करेगा

# सभी फ़ाइलों के लिए कैशिंग हेडर
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
