jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated from v2 to v3
      
      - name: Set up Java
        uses: actions/setup-java@v3  # Updated from v1 to v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Build APK
        run: ./gradlew assembleDebug
      
      - name: Upload APK
        uses: actions/upload-artifact@v3  # 🔥 Update v2 → v3
        with:
          name: app-release
          path: app/build/outputs/apk/debug/app-debug.apk
